-- BookStore Supabase schema + sample data for local development.
-- Run this in a NEW Supabase project: SQL Editor -> New query -> Run.
-- WARNING: this resets the listed tables.

drop table if exists public."ViewHistory" cascade;
drop table if exists public."OrderItem" cascade;
drop table if exists public."Order" cascade;
drop table if exists public."CartItem" cascade;
drop table if exists public."Cart" cascade;
drop table if exists public."Review" cascade;
drop table if exists public."OTP" cascade;
drop table if exists public."Payment" cascade;
drop table if exists public."Address" cascade;
drop table if exists public."Voucher" cascade;
drop table if exists public."Shipment" cascade;
drop table if exists public."BookPublisher" cascade;
drop table if exists public."Publishers" cascade;
drop table if exists public."BookCategory" cascade;
drop table if exists public."BookAuthor" cascade;
drop table if exists public."BookImages" cascade;
drop table if exists public."Book" cascade;
drop table if exists public."Categories" cascade;
drop table if exists public."Authors" cascade;
drop table if exists public."Customer" cascade;

create table public."Customer" (
  "customerID" integer primary key,
  "email" text not null unique,
  "password" text not null,
  "fullName" text,
  "phoneNumber" text,
  "joinDay" timestamptz default now()
);

create table public."Authors" (
  "authorID" integer primary key,
  "authorName" text not null,
  "biography" text,
  "avatar" text
);

create table public."Categories" (
  "categoryID" integer primary key,
  "categoryName" text not null
);

create table public."Publishers" (
  "publisherID" integer primary key,
  "publisherName" text not null
);

create table public."Book" (
  "bookID" integer primary key,
  "title" text not null,
  "author" text,
  "price" numeric(12,2) not null default 0,
  "description" text,
  "language" text,
  "format" text,
  "pageCount" integer,
  "variantLabel" text,
  "idGroup" integer,
  "createdAt" timestamptz default now()
);

create table public."BookImages" (
  "imageID" integer generated by default as identity primary key,
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "imageURL" text not null,
  "isPrimary" boolean default false
);

create table public."BookAuthor" (
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "idAuthor" integer not null references public."Authors"("authorID") on delete cascade,
  primary key ("idBook", "idAuthor")
);

create table public."BookCategory" (
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "idCategory" integer not null references public."Categories"("categoryID") on delete cascade,
  primary key ("idBook", "idCategory")
);

create table public."BookPublisher" (
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "idPublisher" integer not null references public."Publishers"("publisherID") on delete cascade,
  primary key ("idBook", "idPublisher")
);

create table public."Address" (
  "addressID" integer generated by default as identity primary key,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade,
  "receiverName" text not null,
  "addressString" text not null
);

create table public."Payment" (
  "paymentID" integer generated by default as identity primary key,
  -- Kept only because vnpayController.js selects Payment.id in one legacy path.
  -- paymentID is the real primary key used by the app.
  "id" integer unique,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade,
  "paymentMethod" text not null,
  "status" text,
  "vnpToken" text,
  "maskedCardNumber" text,
  "vnpCardType" text
);

create table public."OTP" (
  "otpID" integer generated by default as identity primary key,
  "otpCode" text not null,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade,
  "expiredAt" timestamptz not null
);

create table public."Review" (
  "reviewID" integer generated by default as identity primary key,
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade,
  "rating" numeric(2,1) not null check ("rating" >= 1 and "rating" <= 5),
  "comment" text,
  "createdAt" timestamptz default now(),
  unique ("idBook", "idCustomer")
);

create table public."Cart" (
  "cartID" integer generated by default as identity primary key,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade,
  "updateAt" timestamptz default now()
);

create table public."CartItem" (
  "cartItemID" integer generated by default as identity primary key,
  "idCart" integer not null references public."Cart"("cartID") on delete cascade,
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "quantity" integer not null default 1,
  unique ("idCart", "idBook")
);

create table public."Voucher" (
  "voucherID" integer generated by default as identity primary key,
  "code" text not null unique,
  "description" text,
  "type" text not null check ("type" in ('PERCENT', 'FIXED')),
  "discountValue" numeric(12,2) not null default 0,
  "minOrderValue" numeric(12,2) not null default 0,
  "expiryDate" timestamptz not null,
  "usageLimit" integer not null default 0
);

create table public."Shipment" (
  "shipmentID" integer generated by default as identity primary key,
  "shipmentMethod" text not null,
  "estimatedDate" text,
  "status" text
);

create table public."Order" (
  "orderID" integer generated by default as identity primary key,
  "orderDate" timestamptz default now(),
  "totalAmount" numeric(12,2) not null default 0,
  "finalAmount" numeric(12,2) not null default 0,
  "status" text,
  "idCustomer" integer not null references public."Customer"("customerID"),
  "idAddress" integer references public."Address"("addressID"),
  "idPayment" integer references public."Payment"("paymentID"),
  "idShipment" integer references public."Shipment"("shipmentID"),
  "idVoucher" integer references public."Voucher"("voucherID"),
  "vnpTransactionNo" text
);

create table public."OrderItem" (
  "orderItemID" integer generated by default as identity primary key,
  "idOrder" integer not null references public."Order"("orderID") on delete cascade,
  "idBook" integer not null references public."Book"("bookID"),
  "quantity" integer not null default 1
);

create table public."ViewHistory" (
  "viewHistoryID" integer generated by default as identity primary key,
  "viewAt" timestamptz default now(),
  "idBook" integer not null references public."Book"("bookID") on delete cascade,
  "idCustomer" integer not null references public."Customer"("customerID") on delete cascade
);

insert into public."Customer" ("customerID", "email", "password", "fullName", "phoneNumber", "joinDay") values
(1, 'demo@bookstore.local', '$2b$10$JgZkEq1PsjjzL6pRICjqVeypWdQSGnCo7AjkK/12HIRq3N1yBOMNi', 'Demo User', '0900000000', now());

insert into public."Authors" ("authorID", "authorName", "biography") values
(1, 'Dale Carnegie', 'Self-help author.'),
(2, 'Paulo Coelho', 'Brazilian novelist.'),
(3, 'J. K. Rowling', 'Fantasy author.'),
(4, 'Yuval Noah Harari', 'Historian and writer.'),
(5, 'Robert Kiyosaki', 'Personal finance author.');

insert into public."Categories" ("categoryID", "categoryName") values
(1, 'Ky nang song'),
(2, 'Tieu thuyet'),
(3, 'Kinh te'),
(4, 'Lich su'),
(5, 'Thieu nhi');

insert into public."Publishers" ("publisherID", "publisherName") values
(1, 'NXB Tre'),
(2, 'NXB Tong hop'),
(3, 'Bloomsbury');

insert into public."Book" ("bookID", "title", "author", "price", "description", "language", "format", "pageCount", "variantLabel", "idGroup", "createdAt") values
(1, 'Dac Nhan Tam', 'Dale Carnegie', 1.20, 'Cuon sach kinh dien ve giao tiep va ung xu.', 'English', 'Paperback', 320, 'Ban thuong', 100, now() - interval '1 day'),
(2, 'Nha Gia Kim', 'Paulo Coelho', 1.05, 'Hanh trinh di tim kho bau va y nghia cuoc song.', 'English', 'Paperback', 240, 'Ban thuong', 101, now() - interval '2 days'),
(3, 'Harry Potter va Hon da Phu thuy', 'J. K. Rowling', 1.50, 'Cau chuyen dau tien ve the gioi phu thuy Harry Potter.', 'English', 'Hardcover', 360, 'Hardcover', 102, now() - interval '3 days'),
(4, 'Sapiens Luoc su loai nguoi', 'Yuval Noah Harari', 1.80, 'Tong quan lich su phat trien cua nhan loai.', 'English', 'Paperback', 520, 'Ban thuong', 103, now() - interval '4 days'),
(5, 'Cha Giau Cha Ngheo', 'Robert Kiyosaki', 1.25, 'Bai hoc tai chinh ca nhan va tu duy dau tu.', 'English', 'Paperback', 336, 'Ban thuong', 104, now() - interval '5 days'),
(6, 'Harry Potter and the Chamber of Secrets', 'J. K. Rowling', 1.55, 'The next book in the Harry Potter series.', 'English', 'Hardcover', 380, 'Hardcover', 102, now() - interval '6 days');

insert into public."BookImages" ("idBook", "imageURL", "isPrimary") values
(1, 'https://covers.openlibrary.org/b/isbn/0671027034-L.jpg', true),
(2, 'https://covers.openlibrary.org/b/isbn/0061122416-L.jpg', true),
(3, 'https://covers.openlibrary.org/b/isbn/059035342X-L.jpg', true),
(4, 'https://covers.openlibrary.org/b/isbn/0062316095-L.jpg', true),
(5, 'https://covers.openlibrary.org/b/isbn/1612680194-L.jpg', true),
(6, 'https://covers.openlibrary.org/b/isbn/0439064872-L.jpg', true);

insert into public."BookAuthor" ("idBook", "idAuthor") values
(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 3);

insert into public."BookCategory" ("idBook", "idCategory") values
(1, 1), (2, 2), (3, 5), (3, 2), (4, 4), (5, 3), (6, 5), (6, 2);

insert into public."BookPublisher" ("idBook", "idPublisher") values
(1, 1), (2, 1), (3, 3), (4, 2), (5, 2), (6, 3);

insert into public."Address" ("idCustomer", "receiverName", "addressString") values
(1, 'Demo User', 'Quan 1, TP HCM');

insert into public."Payment" ("idCustomer", "paymentMethod", "status") values
(1, 'Cash on Delivery (COD)', 'Active'),
(1, 'Chuyen khoan ngan hang', 'Active');

insert into public."Shipment" ("shipmentMethod", "estimatedDate", "status") values
('Standard delivery', '3-5 days', 'Active'),
('Express delivery', '1-2 days', 'Active');

insert into public."Voucher" ("code", "description", "type", "discountValue", "minOrderValue", "expiryDate", "usageLimit") values
('BOOK10', '10 percent discount', 'PERCENT', 10, 1, now() + interval '90 days', 100),
('FREESHIP', 'Shipping fee discount', 'FIXED', 0.2, 1, now() + interval '90 days', 100);

insert into public."Review" ("idBook", "idCustomer", "rating", "comment", "createdAt") values
(1, 1, 5, 'Sach hay va de ap dung.', now() - interval '3 days'),
(2, 1, 4, 'Noi dung truyen cam hung.', now() - interval '2 days'),
(3, 1, 5, 'Rat phu hop de doc giai tri.', now() - interval '1 day');

-- Keep Supabase REST access simple for this student/local backend.
-- If you later enable RLS, create explicit policies instead of relying on these grants.
alter table public."Customer" disable row level security;
alter table public."Authors" disable row level security;
alter table public."Categories" disable row level security;
alter table public."Publishers" disable row level security;
alter table public."Book" disable row level security;
alter table public."BookImages" disable row level security;
alter table public."BookAuthor" disable row level security;
alter table public."BookCategory" disable row level security;
alter table public."BookPublisher" disable row level security;
alter table public."Address" disable row level security;
alter table public."Payment" disable row level security;
alter table public."OTP" disable row level security;
alter table public."Review" disable row level security;
alter table public."Cart" disable row level security;
alter table public."CartItem" disable row level security;
alter table public."Voucher" disable row level security;
alter table public."Shipment" disable row level security;
alter table public."Order" disable row level security;
alter table public."OrderItem" disable row level security;
alter table public."ViewHistory" disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant usage, select on all sequences in schema public to anon, authenticated, service_role;
